apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: custom-java-spring-boot2-gitops-task
  namespace: kabanero
  author: Hemankita Perabathini
spec:
  inputs:
    resources:
      - name: git-source
        type: git
      - name: docker-image
        type: image
    params:
      - name: js-image
        type: string
        default: node:12-stretch
      - name: gitRepo
        type: string
      - name: gitOrg
        type: string
      - name: gitOpsRepo
        type: string
        default: gitops-dev
  steps:
    - name: update-gitops-repo
      image: $(inputs.params.js-image)
      workingdir: $(inputs.resources.git-source.path)
      env:
        - name: GIT_USER_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: git-credentials-storefront
              key: username
              optional: true
        - name: GITHUB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-credentials-storefront
              key: password
              optional: true
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e

          echo "Cloning the below repository"
          echo $(inputs.params.gitOrg)
          echo $(inputs.params.gitOpsRepo)

          # clone repo
          git clone https://github.com/$(inputs.params.gitOrg)/$(inputs.params.gitOpsRepo).git
          cd $(inputs.params.gitOpsRepo)/$(inputs.params.gitRepo)

          # update value for key applicationImage
          sed -i '/applicationImage:/c\  applicationImage: $(inputs.resources.docker-image.url)' ./appsody/app-deploy.yaml

          # verify the value for key applicationImage got updated
          cat ./appsody/app-deploy.yaml | grep "image"

          # This email is not used and it is not valid, you can ignore but git requires it
          git config --global user.email "tekton_ci@storefront.com"
          git config --global user.name "tekton"

          echo $(inputs.resources.git-source.path)

          # push changes to git
          git add .
          git commit -m "Tekton CI commit"
          git remote rm origin
          git remote add origin https://${GIT_USER_ACCOUNT}:${GITHUB_API_TOKEN}@github.com/$(inputs.params.gitOrg)/$(inputs.params.gitOpsRepo).git > /dev/null 2>&1
          git push origin master
