apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: storefront-nodejs-pl
  namespace: kabanero
spec:
  params:
  - description: The event type
    name: event-type
    type: string
  - description: The event ref
    name: event-ref
    type: string
  - description: Name of the git org.
    name: gitOrg
    type: string
  - description: Name of the gitOps repo.
    name: gitOpsRepo
    type: string
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: validate-stack-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
    taskRef:
      kind: Task
      name: nodejs-validate-stack-task
  - name: sonarqube-task
    resources:
      inputs:
        - name: git-source
          resource: git-source
    runAfter:
    - validate-stack-task
    taskRef:
      kind: Task
      name: nodejs-sonarqube-task
  - name: test-task
    resources:
      inputs:
        - name: git-source
          resource: git-source
    runAfter:
    - sonarqube-task
    taskRef:
      kind: Task
      name: nodejs-test-task
  - name: pact-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
    runAfter:
    - test-task
    taskRef:
      kind: Task
      name: nodejs-pact-broker-task
  - name: build-push-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
      - name: git-source
        resource: git-source
    runAfter:
    - pact-task
    taskRef:
      kind: Task
      name: nodejs-build-push-task
  - name: image-scan-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
    runAfter:
    - build-push-task
    taskRef:
      kind: Task
      name: nodejs-image-scan-task
  - name: deploy-task
    conditions:
    - conditionRef: nodejs-deployment-condition
      params:
      - name: event-type
        value: $(params.event-type)
      - name: event-ref
        value: $(params.event-ref)
    resources:
      inputs:
      - from:
        - build-push-task
        name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
    runAfter:
    - image-scan-task
    taskRef:
      kind: Task
      name: nodejs-deploy-task
  - name: health-check-task
    resources:
      inputs:
        - name: git-source
          resource: git-source
    runAfter:
      - deploy-task
    taskRef:
      kind: Task
      name: nodejs-health-check-task
  - name: gitops-task
    resources:
      inputs:
        - name: git-source
          resource: git-source
        - name: docker-image
          resource: docker-image
    params:
        - name: gitOrg
          value: "$(params.gitOrg)"
        - name: gitOpsRepo
          value: "$(params.gitOpsRepo)"
    runAfter:
    - health-check-task
    taskRef:
      kind: Task
      name: nodejs-gitops-task
